// Mocks generated by Mockito 5.4.6 from annotations
// in nerack/test/features/authentication/domain/usecases/login_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nerack/core/errors/failures.dart' as _i5;
import 'package:nerack/features/authentication/domain/entities/auth_request.dart'
    as _i7;
import 'package:nerack/features/authentication/domain/entities/auth_response.dart'
    as _i6;
import 'package:nerack/features/authentication/domain/entities/user_entity.dart'
    as _i8;
import 'package:nerack/features/authentication/domain/repositories/auth_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResponse>> login(
    _i7.LoginRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResponse>>.value(
                  _FakeEither_0<_i5.Failure, _i6.AuthResponse>(
                    this,
                    Invocation.method(#login, [request]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResponse>> register(
    _i7.RegisterRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResponse>>.value(
                  _FakeEither_0<_i5.Failure, _i6.AuthResponse>(
                    this,
                    Invocation.method(#register, [request]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AuthResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.RefreshTokenResponse>>
  refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.RefreshTokenResponse>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.RefreshTokenResponse>(
                    this,
                    Invocation.method(#refreshToken, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.RefreshTokenResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> forgotPassword(
    _i7.ForgotPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [request]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#forgotPassword, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> resetPassword(
    _i7.ResetPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.UserEntity>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i8.UserEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i8.UserEntity>(
                    this,
                    Invocation.method(#getCurrentUser, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.UserEntity>> updateProfile(
    _i8.UserEntity? user,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [user]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i8.UserEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i8.UserEntity>(
                    this,
                    Invocation.method(#updateProfile, [user]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.UserEntity>>);

  @override
  _i4.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> getStoredToken() =>
      (super.noSuchMethod(
            Invocation.method(#getStoredToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);
}
